name: Cron Job

on:
   push:
      branches:
         - main
   schedule:
      - cron: "*/5 * * * *"

jobs:
   cron-job:
      runs-on: ubuntu-latest
      steps:
         - run: echo "Cron job running"