name : Multiple Workflows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, First World!"
  second-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, Second World!"