name: Dependent Job

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  dependent-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, World!"

  dependent-job-2:
    runs-on: ubuntu-latest
    needs: [dependent-job]
    steps:
      - run: echo "Hello, World!"

  dependent-job-3:
    runs-on: ubuntu-latest
    needs: [dependent-job, dependent-job-2]
    steps:
      - run: echo "Hello, World!"