name: Condition Workflow

on:
  push: 
    paths: 
      - "backend/**"

jobs:
  condition-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Build Backend Image
        run: echo "Hello, World!"
